// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barrage.proto

package top.houry.netty.barrage.proto;

public final class BarrageProto {
    private BarrageProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface BarrageResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:BarrageResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 videoId = 1;</code>
         */
        int getVideoId();

        /**
         * <code>string videName = 2;</code>
         */
        java.lang.String getVideName();
        /**
         * <code>string videName = 2;</code>
         */
        com.google.protobuf.ByteString
        getVideNameBytes();
    }
    /**
     * Protobuf type {@code BarrageResponse}
     */
    public  static final class BarrageResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:BarrageResponse)
            BarrageResponseOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use BarrageResponse.newBuilder() to construct.
        private BarrageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private BarrageResponse() {
            videoId_ = 0;
            videName_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private BarrageResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            videoId_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            videName_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_BarrageResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_BarrageResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.class, top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.Builder.class);
        }

        public static final int VIDEOID_FIELD_NUMBER = 1;
        private int videoId_;
        /**
         * <code>int32 videoId = 1;</code>
         */
        public int getVideoId() {
            return videoId_;
        }

        public static final int VIDENAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object videName_;
        /**
         * <code>string videName = 2;</code>
         */
        public java.lang.String getVideName() {
            java.lang.Object ref = videName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                videName_ = s;
                return s;
            }
        }
        /**
         * <code>string videName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getVideNameBytes() {
            java.lang.Object ref = videName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                videName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (videoId_ != 0) {
                output.writeInt32(1, videoId_);
            }
            if (!getVideNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, videName_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (videoId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, videoId_);
            }
            if (!getVideNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, videName_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof top.houry.netty.barrage.proto.BarrageProto.BarrageResponse)) {
                return super.equals(obj);
            }
            top.houry.netty.barrage.proto.BarrageProto.BarrageResponse other = (top.houry.netty.barrage.proto.BarrageProto.BarrageResponse) obj;

            boolean result = true;
            result = result && (getVideoId()
                    == other.getVideoId());
            result = result && getVideName()
                    .equals(other.getVideName());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + VIDEOID_FIELD_NUMBER;
            hash = (53 * hash) + getVideoId();
            hash = (37 * hash) + VIDENAME_FIELD_NUMBER;
            hash = (53 * hash) + getVideName().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(top.houry.netty.barrage.proto.BarrageProto.BarrageResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code BarrageResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:BarrageResponse)
                top.houry.netty.barrage.proto.BarrageProto.BarrageResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_BarrageResponse_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_BarrageResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.class, top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.Builder.class);
            }

            // Construct using top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                videoId_ = 0;

                videName_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_BarrageResponse_descriptor;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.BarrageResponse getDefaultInstanceForType() {
                return top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.getDefaultInstance();
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.BarrageResponse build() {
                top.houry.netty.barrage.proto.BarrageProto.BarrageResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.BarrageResponse buildPartial() {
                top.houry.netty.barrage.proto.BarrageProto.BarrageResponse result = new top.houry.netty.barrage.proto.BarrageProto.BarrageResponse(this);
                result.videoId_ = videoId_;
                result.videName_ = videName_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof top.houry.netty.barrage.proto.BarrageProto.BarrageResponse) {
                    return mergeFrom((top.houry.netty.barrage.proto.BarrageProto.BarrageResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(top.houry.netty.barrage.proto.BarrageProto.BarrageResponse other) {
                if (other == top.houry.netty.barrage.proto.BarrageProto.BarrageResponse.getDefaultInstance()) return this;
                if (other.getVideoId() != 0) {
                    setVideoId(other.getVideoId());
                }
                if (!other.getVideName().isEmpty()) {
                    videName_ = other.videName_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                top.houry.netty.barrage.proto.BarrageProto.BarrageResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (top.houry.netty.barrage.proto.BarrageProto.BarrageResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int videoId_ ;
            /**
             * <code>int32 videoId = 1;</code>
             */
            public int getVideoId() {
                return videoId_;
            }
            /**
             * <code>int32 videoId = 1;</code>
             */
            public Builder setVideoId(int value) {

                videoId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 videoId = 1;</code>
             */
            public Builder clearVideoId() {

                videoId_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object videName_ = "";
            /**
             * <code>string videName = 2;</code>
             */
            public java.lang.String getVideName() {
                java.lang.Object ref = videName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    videName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string videName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getVideNameBytes() {
                java.lang.Object ref = videName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    videName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string videName = 2;</code>
             */
            public Builder setVideName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                videName_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string videName = 2;</code>
             */
            public Builder clearVideName() {

                videName_ = getDefaultInstance().getVideName();
                onChanged();
                return this;
            }
            /**
             * <code>string videName = 2;</code>
             */
            public Builder setVideNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                videName_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:BarrageResponse)
        }

        // @@protoc_insertion_point(class_scope:BarrageResponse)
        private static final top.houry.netty.barrage.proto.BarrageProto.BarrageResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new top.houry.netty.barrage.proto.BarrageProto.BarrageResponse();
        }

        public static top.houry.netty.barrage.proto.BarrageProto.BarrageResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BarrageResponse>
                PARSER = new com.google.protobuf.AbstractParser<BarrageResponse>() {
            @java.lang.Override
            public BarrageResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BarrageResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<BarrageResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<BarrageResponse> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public top.houry.netty.barrage.proto.BarrageProto.BarrageResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_BarrageResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_BarrageResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rbarrage.proto\"4\n\017BarrageResponse\022\017\n\007vi" +
                        "deoId\030\001 \001(\005\022\020\n\010videName\030\002 \001(\tB-\n\035top.hou" +
                        "ry.netty.barrage.protoB\014BarrageProtob\006pr" +
                        "oto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_BarrageResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_BarrageResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_BarrageResponse_descriptor,
                new java.lang.String[] { "VideoId", "VideName", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
