// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: barrage.proto

package top.houry.netty.barrage.proto;

public final class BarrageProto {
    private BarrageProto() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface BarrageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Barrage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string msgType = 1;</code>
         */
        java.lang.String getMsgType();
        /**
         * <code>string msgType = 1;</code>
         */
        com.google.protobuf.ByteString
        getMsgTypeBytes();

        /**
         * <code>bytes bytesData = 2;</code>
         */
        com.google.protobuf.ByteString getBytesData();
    }
    /**
     * <pre>
     * 总的消息体
     * </pre>
     *
     * Protobuf type {@code Barrage}
     */
    public  static final class Barrage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Barrage)
            BarrageOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Barrage.newBuilder() to construct.
        private Barrage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Barrage() {
            msgType_ = "";
            bytesData_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Barrage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            msgType_ = s;
                            break;
                        }
                        case 18: {

                            bytesData_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_Barrage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_Barrage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            top.houry.netty.barrage.proto.BarrageProto.Barrage.class, top.houry.netty.barrage.proto.BarrageProto.Barrage.Builder.class);
        }

        public static final int MSGTYPE_FIELD_NUMBER = 1;
        private volatile java.lang.Object msgType_;
        /**
         * <code>string msgType = 1;</code>
         */
        public java.lang.String getMsgType() {
            java.lang.Object ref = msgType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msgType_ = s;
                return s;
            }
        }
        /**
         * <code>string msgType = 1;</code>
         */
        public com.google.protobuf.ByteString
        getMsgTypeBytes() {
            java.lang.Object ref = msgType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msgType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BYTESDATA_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString bytesData_;
        /**
         * <code>bytes bytesData = 2;</code>
         */
        public com.google.protobuf.ByteString getBytesData() {
            return bytesData_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getMsgTypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgType_);
            }
            if (!bytesData_.isEmpty()) {
                output.writeBytes(2, bytesData_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getMsgTypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgType_);
            }
            if (!bytesData_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, bytesData_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof top.houry.netty.barrage.proto.BarrageProto.Barrage)) {
                return super.equals(obj);
            }
            top.houry.netty.barrage.proto.BarrageProto.Barrage other = (top.houry.netty.barrage.proto.BarrageProto.Barrage) obj;

            boolean result = true;
            result = result && getMsgType()
                    .equals(other.getMsgType());
            result = result && getBytesData()
                    .equals(other.getBytesData());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getMsgType().hashCode();
            hash = (37 * hash) + BYTESDATA_FIELD_NUMBER;
            hash = (53 * hash) + getBytesData().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.Barrage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(top.houry.netty.barrage.proto.BarrageProto.Barrage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         * 总的消息体
         * </pre>
         *
         * Protobuf type {@code Barrage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Barrage)
                top.houry.netty.barrage.proto.BarrageProto.BarrageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_Barrage_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_Barrage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                top.houry.netty.barrage.proto.BarrageProto.Barrage.class, top.houry.netty.barrage.proto.BarrageProto.Barrage.Builder.class);
            }

            // Construct using top.houry.netty.barrage.proto.BarrageProto.Barrage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                msgType_ = "";

                bytesData_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_Barrage_descriptor;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.Barrage getDefaultInstanceForType() {
                return top.houry.netty.barrage.proto.BarrageProto.Barrage.getDefaultInstance();
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.Barrage build() {
                top.houry.netty.barrage.proto.BarrageProto.Barrage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.Barrage buildPartial() {
                top.houry.netty.barrage.proto.BarrageProto.Barrage result = new top.houry.netty.barrage.proto.BarrageProto.Barrage(this);
                result.msgType_ = msgType_;
                result.bytesData_ = bytesData_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof top.houry.netty.barrage.proto.BarrageProto.Barrage) {
                    return mergeFrom((top.houry.netty.barrage.proto.BarrageProto.Barrage)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(top.houry.netty.barrage.proto.BarrageProto.Barrage other) {
                if (other == top.houry.netty.barrage.proto.BarrageProto.Barrage.getDefaultInstance()) return this;
                if (!other.getMsgType().isEmpty()) {
                    msgType_ = other.msgType_;
                    onChanged();
                }
                if (other.getBytesData() != com.google.protobuf.ByteString.EMPTY) {
                    setBytesData(other.getBytesData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                top.houry.netty.barrage.proto.BarrageProto.Barrage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (top.houry.netty.barrage.proto.BarrageProto.Barrage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object msgType_ = "";
            /**
             * <code>string msgType = 1;</code>
             */
            public java.lang.String getMsgType() {
                java.lang.Object ref = msgType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    msgType_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string msgType = 1;</code>
             */
            public com.google.protobuf.ByteString
            getMsgTypeBytes() {
                java.lang.Object ref = msgType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    msgType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string msgType = 1;</code>
             */
            public Builder setMsgType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msgType_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string msgType = 1;</code>
             */
            public Builder clearMsgType() {

                msgType_ = getDefaultInstance().getMsgType();
                onChanged();
                return this;
            }
            /**
             * <code>string msgType = 1;</code>
             */
            public Builder setMsgTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msgType_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString bytesData_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>bytes bytesData = 2;</code>
             */
            public com.google.protobuf.ByteString getBytesData() {
                return bytesData_;
            }
            /**
             * <code>bytes bytesData = 2;</code>
             */
            public Builder setBytesData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                bytesData_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bytes bytesData = 2;</code>
             */
            public Builder clearBytesData() {

                bytesData_ = getDefaultInstance().getBytesData();
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Barrage)
        }

        // @@protoc_insertion_point(class_scope:Barrage)
        private static final top.houry.netty.barrage.proto.BarrageProto.Barrage DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new top.houry.netty.barrage.proto.BarrageProto.Barrage();
        }

        public static top.houry.netty.barrage.proto.BarrageProto.Barrage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Barrage>
                PARSER = new com.google.protobuf.AbstractParser<Barrage>() {
            @java.lang.Override
            public Barrage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Barrage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Barrage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Barrage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public top.houry.netty.barrage.proto.BarrageProto.Barrage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface HeartBeatRespOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HeartBeatResp)
            com.google.protobuf.MessageOrBuilder {
    }
    /**
     * <pre>
     * 心跳回复包
     * </pre>
     *
     * Protobuf type {@code HeartBeatResp}
     */
    public  static final class HeartBeatResp extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HeartBeatResp)
            HeartBeatRespOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use HeartBeatResp.newBuilder() to construct.
        private HeartBeatResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private HeartBeatResp() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private HeartBeatResp(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartBeatResp_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartBeatResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.class, top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.Builder.class);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp)) {
                return super.equals(obj);
            }
            top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp other = (top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp) obj;

            boolean result = true;
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         * 心跳回复包
         * </pre>
         *
         * Protobuf type {@code HeartBeatResp}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HeartBeatResp)
                top.houry.netty.barrage.proto.BarrageProto.HeartBeatRespOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartBeatResp_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartBeatResp_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.class, top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.Builder.class);
            }

            // Construct using top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartBeatResp_descriptor;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp getDefaultInstanceForType() {
                return top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.getDefaultInstance();
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp build() {
                top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp buildPartial() {
                top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp result = new top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp) {
                    return mergeFrom((top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp other) {
                if (other == top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:HeartBeatResp)
        }

        // @@protoc_insertion_point(class_scope:HeartBeatResp)
        private static final top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp();
        }

        public static top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HeartBeatResp>
                PARSER = new com.google.protobuf.AbstractParser<HeartBeatResp>() {
            @java.lang.Override
            public HeartBeatResp parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HeartBeatResp(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HeartBeatResp> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HeartBeatResp> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public top.houry.netty.barrage.proto.BarrageProto.HeartBeatResp getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface HeartHeatReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:HeartHeatReq)
            com.google.protobuf.MessageOrBuilder {
    }
    /**
     * <pre>
     * 心跳请求包
     * </pre>
     *
     * Protobuf type {@code HeartHeatReq}
     */
    public  static final class HeartHeatReq extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:HeartHeatReq)
            HeartHeatReqOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use HeartHeatReq.newBuilder() to construct.
        private HeartHeatReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private HeartHeatReq() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private HeartHeatReq(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartHeatReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartHeatReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.class, top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.Builder.class);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq)) {
                return super.equals(obj);
            }
            top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq other = (top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq) obj;

            boolean result = true;
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * <pre>
         * 心跳请求包
         * </pre>
         *
         * Protobuf type {@code HeartHeatReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:HeartHeatReq)
                top.houry.netty.barrage.proto.BarrageProto.HeartHeatReqOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartHeatReq_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartHeatReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.class, top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.Builder.class);
            }

            // Construct using top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return top.houry.netty.barrage.proto.BarrageProto.internal_static_HeartHeatReq_descriptor;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq getDefaultInstanceForType() {
                return top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.getDefaultInstance();
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq build() {
                top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq buildPartial() {
                top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq result = new top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq(this);
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq) {
                    return mergeFrom((top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq other) {
                if (other == top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq.getDefaultInstance()) return this;
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:HeartHeatReq)
        }

        // @@protoc_insertion_point(class_scope:HeartHeatReq)
        private static final top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq();
        }

        public static top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<HeartHeatReq>
                PARSER = new com.google.protobuf.AbstractParser<HeartHeatReq>() {
            @java.lang.Override
            public HeartHeatReq parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new HeartHeatReq(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<HeartHeatReq> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<HeartHeatReq> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public top.houry.netty.barrage.proto.BarrageProto.HeartHeatReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Barrage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Barrage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HeartBeatResp_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HeartBeatResp_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_HeartHeatReq_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_HeartHeatReq_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rbarrage.proto\"-\n\007Barrage\022\017\n\007msgType\030\001 " +
                        "\001(\t\022\021\n\tbytesData\030\002 \001(\014\"\017\n\rHeartBeatResp\"" +
                        "\016\n\014HeartHeatReqB-\n\035top.houry.netty.barra" +
                        "ge.protoB\014BarrageProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_Barrage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Barrage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Barrage_descriptor,
                new java.lang.String[] { "MsgType", "BytesData", });
        internal_static_HeartBeatResp_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_HeartBeatResp_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HeartBeatResp_descriptor,
                new java.lang.String[] { });
        internal_static_HeartHeatReq_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_HeartHeatReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_HeartHeatReq_descriptor,
                new java.lang.String[] { });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
